-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 23-04-2021 a las 15:31:31
-- Versión del servidor: 10.4.17-MariaDB
-- Versión de PHP: 7.4.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `plazaamericana`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `business`
--

CREATE TABLE `business` (
  `id` bigint(20) NOT NULL,
  `token` char(8) NOT NULL,
  `name` text NOT NULL,
  `description` text NOT NULL,
  `turn` text NOT NULL,
  `local` text NOT NULL,
  `email` text DEFAULT NULL,
  `phone` text DEFAULT NULL,
  `whatsapp` text DEFAULT NULL,
  `facebook` text DEFAULT NULL,
  `instagram` text DEFAULT NULL,
  `website` text DEFAULT NULL,
  `background` text NOT NULL,
  `cover` text NOT NULL,
  `logotype` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `business`
--

INSERT INTO `business` (`id`, `token`, `name`, `description`, `turn`, `local`, `email`, `phone`, `whatsapp`, `facebook`, `instagram`, `website`, `background`, `cover`, `logotype`) VALUES
(1, 'bhk8d27e', 'Artesanías Maya Tolosa', '{\"es\":\"Somos una familia Yucateca que valora el trabajo artesanal de nuestro pueblo, apoyamos lo que se produce en Yucatán. La energía de nuestra cultura, en cada artículo que vendemos, una parte de la esencia Maya, las telas, los hilos, los colores y diseños hechos con amor. Fomentamos nuevos diseños continuamente para que pueda disfrutar de la gran variedad que tenemos en nuestra Tienda. Representamos el Sombrero Yucateco, lujo del Mayab, digno de elegancia, el Jipi Japa, hecho en cuevas húmedas por manos llenas de gran pasión por el arte, gente sencilla, llena de gran talento.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Artesanías', '34', NULL, NULL, NULL, '{\"url\":\"\",\"user\":\"\"}', '{\"url\":\"\",\"user\":\"\"}', 'www.artesaniasmayastolosa.com', 'tolosa_bg.png', 'tolosa_cv.png', 'tolosa_lg.png'),
(2, 'jhy789k2', 'Bellezas de Cuba', '{\"es\":\"Somos un pequeño negocio ubicado en Progreso, principal playa de la ciudad de Mérida, Yucatán. Completamente realizados en Cuba, nuestros productos artesanales provienen directamente de talentosas manos de cubanas y cubanos. Nuestra selección proviene de 4 zonas diferentes de Cuba: Habana, Matanzas, Trinidad (Sancti Spíritu) y Gibara (Holguín). Nos especializamos en la venta de ropa con diseños a crochet únicos y exclusivos de nuestra tierra. Con más de 100 modelos, hemos logrado completar una colección de moda femenina para todas las edades y gustos. Siempre con materiales de algodón y seda, te brindamos un estilo fresco, diferente y divertido para cumplir con tus espectativas de un estilo casual de playa. Sin embargo también contamos en nuestra colección con piezas especiales de alto nivel de expertise de crochet, la complejidad de las piezas se concentra en la técnica utilizada y las más de 100 horas de dedicación que se necesitan.  Ven y descubre con nosotros lo que la cultura artesanal de diferentes regiones de Cuba te puede ofrecer!\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Artesanías', '7-B', NULL, NULL, NULL, '{\"url\":\"https://facebook.com/bellezasdecubaa\",\"user\":\"bellezasdecubaa\"}', '{\"url\":\"https://facebook.com/bellezasdecuba\",\"user\":\"bellezasdecuba\"}', NULL, 'cuba_bg.png', 'cuba_cv.png', 'cuba_lg.png'),
(3, 'jh76d92h', 'El Bahúl', '{\"es\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Ropa', '22 y 23', NULL, NULL, NULL, '{\"url\":\"\",\"user\":\"\"}', '{\"url\":\"\",\"user\":\"\"}', NULL, 'bahul_bg.png', 'bahul_cv.png', 'bahul_lg.png'),
(4, 'h76re98d', 'Enzo Men', '{\"es\":\"Venta de Ropa de Dama, Caballero y Niño de Lino 100 % italiano y accesorios artesanales. Somos fabricantes y diseñadores de todos los modelos de nuestra propia marca y trabajamos con artesanos de la región\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Ropa', '00', NULL, NULL, NULL, '{\"url\":\"https://facebook.com/enzomenmid\",\"user\":\"enzomenmid\"}', '{\"url\":\"https://instagram.com/enzomenmid\",\"user\":\"enzomenmid\"}', 'www.enzomen.com', 'enzo_bg.png', 'enzo_cv.png', 'enzo_lg.png'),
(5, 'mk86ge98', 'Fiesta Snak', '{\"es\":\"Fiesta Snack es una cafetería en la cual uno puede venir a relajarse con un buen desayuno, disfrutando de una rica torta de empanizado o de alguna de sus variedades, al igual que de una ensalada Rusa, sopa fría o simplemente tomar un café con galletas. En los almuerzos pueden disfrutar de rica comida casera, cómo pueden ser unos ricos chilaquiles, kibis, empanadas, sopes panuchos, etc. O simplemente matar el hambre con unas papas, refrescos o algún postre, ya sean muffins, brownies, panes de queso etc. Fiesta Snack abrió sus puertas en los primeros años del centro comercial plaza América, y desde entonces sigue sirviendo alegría y buenos momentos a todo aquel que lo visite y apoyandolos en estos momentos difíciles.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Comida', '16 y 17', NULL, NULL, NULL, '{\"url\":\"\",\"user\":\"\"}', '{\"url\":\"\",\"user\":\"\"}', NULL, 'fiesta_bg.png', 'fiesta_cv.png', 'fiesta_lg.png'),
(6, 'mnbvgtyk', 'La Yucateca', '{\"es\":\"La Yucateca es una casa de artesanías comprometida a trabajar con artesanos yucatecos, dejando huella en la industria del vestido, ofreciendo a nuestros clientes prendas vanguardistas de la mejor calidad.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Ropa', '63', NULL, NULL, NULL, '{\"url\":\"https://www.facebook.com/LaYucatecaMeridaa\",\"user\":\"LaYucatecaMeridaa\"}', '{\"url\":\"https://www.instagram.com/_layucateca/\",\"user\":\"_layucateca\"}', NULL, 'yucateca_bg.png', 'yucateca_cv.png', 'yucateca_lg.png'),
(7, 'hydg736t', 'Ursula Aldana Atuendo', '{\"es\":\"Marca 100% Yucateca. Llevamos 15 años diseñando y elaborando ropa y accesorios para toda la familia en colaboración con artesanos de la región. Hacemos envíos a toda la república.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Ropa', '00', NULL, NULL, NULL, '{\"url\":\"https://facebook.com/1Atuendo\",\"user\":\"1Atuendo\"}', '{\"url\":\"https://instagram-com/atuendo99\",\"user\":\"atuendo99\"}', NULL, 'ursula_bg.png', 'ursula_cv.png', 'ursula_lg.png'),
(8, '09h6g538', 'Zelva Moda', '{\"es\":\"Somos una empresa cien por ciento mexicana con prendas y accesorios elaboradas por diseñadores y artesanos mexicanos exclusivos de nuestra marca. Conócenos y anímate de #artemexicano\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Ropa', '29', NULL, NULL, NULL, '{\"url\":\"https://facebook.com/zelvamoda\",\"user\":\"zelvamoda\"}', '{\"url\":\"https://facebook.com/zelvamoda\",\"user\":\"zelvamoda\"}', 'www.zelvamoda.com', 'zelva_bg.png', 'zelva_cv.png', 'zelva_lg.png'),
(9, 'hy786et5', 'Chilli\'s', '{\"es\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Comida', '00', NULL, NULL, NULL, '{\"url\":\"\",\"user\":\"\"}', '{\"url\":\"\",\"user\":\"\"}', NULL, 'chillis_bg.jpeg', 'chillis_cv.jpeg', 'chillis_lg.svg'),
(10, 'loikjyg6', 'Abito', '{\"es\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Ropa', '00', NULL, NULL, NULL, '{\"url\":\"\",\"user\":\"\"}', '{\"url\":\"\",\"user\":\"\"}', NULL, 'abito_bg.jpg', 'abito_cv.jpg', 'abito_lg.png'),
(11, '098hyuis', 'Dulcería La Mexicana', '{\"es\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Comida', '00', NULL, NULL, NULL, '{\"url\":\"\",\"user\":\"\"}', '{\"url\":\"\",\"user\":\"\"}', NULL, 'mexicana_bg.jpg', 'mexicana_cv.jpg', 'mexicana_lg.png'),
(12, 'kjhgfdrt', 'La Platería', '{\"es\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\",\"en\":\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a.\"}', 'Artesanías', '00', NULL, NULL, NULL, '{\"url\":\"\",\"user\":\"\"}', '{\"url\":\"\",\"user\":\"\"}', NULL, 'plateria_bg.png', 'plateria_cv.png', 'plateria_lg.png');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `business`
--
ALTER TABLE `business`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `business`
--
ALTER TABLE `business`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
